import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import Cursor from "@/components/Cursor";
import Loader from "@/components/Loader";
import Overlay from "@/components/Overlay";
import { IBM_Plex_Sans } from "next/font/google";
import LenisScroll from "@/components/LenisScroll";

const IBM = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={`${IBM.className}`}>
      <body>
        <Overlay />
        <Loader />
        <LenisScroll>
          <Cursor />
          <Header />
          {children}
          <Footer />
        </LenisScroll>
      </body>
    </html>
  );
}
