import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";


import Overlay from "@/components/Overlay";
import { IBM_Plex_Sans } from "next/font/google";

const IBM = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={`${IBM.className}`}>
      <body>
        <Overlay />
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
